In [4]:
from music21 import converter, note, chord, articulations

# Load the music file
score = converter.parse('example.mxl')

# Extract ground truth fingerings
ground_truth_labels = []
for part in score.parts:
    for element in part.flat.notes:
        if isinstance(element, note.Note):
            # Check for fingering articulations
            fingering = None
            for articulation in element.articulations:
                if isinstance(articulation, articulations.Fingering):
                    fingering = articulation.fingerNumber
                    break
            ground_truth_labels.append(fingering if fingering is not None else -1)
        elif isinstance(element, chord.Chord):
            for n in element.notes:
                fingering = None
                for articulation in n.articulations:
                    if isinstance(articulation, articulations.Fingering):
                        fingering = articulation.fingerNumber
                        break
                ground_truth_labels.append(fingering if fingering is not None else -1)

print("Extracted Ground Truth Fingerings:", ground_truth_labels)


Extracted Ground Truth Fingerings: [2, 5, -1, 3, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, 4, -1, -1, -1, -1, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, -1, -1, -1, -1, 3, -1, 3, -1, 3, -1, 4, -1, -1, 4, -1, -1, 1, -1, -1, -1, 5, 2, 3, -1, -1, -1, -1, -1, -1, -1, 3, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, -1, 3, 2, 1, 3, -1, -1, -1, -1, 4, -1, 4, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 5, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5, 4, 3, 1, 4, 3, 2, -1, 2, 3, -1, -1, 3, 2, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,

E:\xlpro-model\venv\lib\site-packages\music21\stream\base.py:3689: Music21DeprecationWarning: .flat is deprecated.  Call .flatten() instead
  return self.iter().getElementsByClass(classFilterList)


In [5]:
from music21 import converter, articulations, note, chord

def extract_predictions_from_file(file_path):
    """
    Extract predictions from the modified example file.
    """
    score = converter.parse(file_path)
    predictions = []

    for element in score.flat.notes:
        if isinstance(element, note.Note):
            for articulation in element.articulations:
                if isinstance(articulation, articulations.Fingering):
                    predictions.append(articulation.fingerNumber)
                    break
            else:
                predictions.append(-1)  # No fingering provided
        elif isinstance(element, chord.Chord):
            for n in element.notes:
                for articulation in n.articulations:
                    if isinstance(articulation, articulations.Fingering):
                        predictions.append(articulation.fingerNumber)
                        break
                else:
                    predictions.append(-1)  # No fingering provided

    return predictions

# Extract predictions from the modified file
predicted_fingerings = extract_predictions_from_file('modified_example.mxl')
print(f"Extracted Predictions: {predicted_fingerings}")


Extracted Predictions: [-3, 2, -3, -1, -1, 2, -5, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 3, 1, 1, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 3, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, -3, 3, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 3, 2, 2, 1, 2, 2, 2, -1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, -3, 2, 2, 2, 2, 2, 2, 2, 1, 3, 3, 2, 1, 1, 2, 2, 2, 1, 2, 2, 3, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, -3, 2, 3, 2, 2, 2, -3, 2, 2, -3, 3, 2, -3, 2, 1, 2, -3, 2, 2, 1, 2, 1, 2, 1, -3, 3, 2, -1, -3, 1, -3, -3, 2, -3, -3, 2, -3, -2, 2, -2, -3, 1, -3, -3, 2, -3, -3, 1, -3, -3, 2, 2, 2, 2, 2, 2, -3, -3, 2, -3, 1, 2, -3, 2, 2, -3, -2, 2, -2, 1, 1, 2, -3, 1, -3, 1, -3, 1, -3, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, -3, 1, -2, 2, 2, 1, 2, 1, 2, -3, 2, -3

In [6]:
# Align lengths between ground truth and predictions
if len(predicted_fingerings) > len(ground_truth_labels):
    predicted_fingerings = predicted_fingerings[:len(ground_truth_labels)]  # Trim excess
elif len(predicted_fingerings) < len(ground_truth_labels):
    predicted_fingerings.extend([-1] * (len(ground_truth_labels) - len(predicted_fingerings)))  # Pad with -1


In [7]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
import numpy as np

# Convert to numpy arrays for evaluation
predicted_fingerings = np.array(predicted_fingerings)
ground_truth_labels = np.array(ground_truth_labels)

# Filter out invalid labels (-1) from both lists
valid_indices = ground_truth_labels != -1
valid_ground_truth = ground_truth_labels[valid_indices]
valid_predictions = predicted_fingerings[valid_indices]

# Calculate accuracy
accuracy = accuracy_score(valid_ground_truth, valid_predictions)
print(f"Accuracy: {accuracy:.2f}")

# Calculate F1 Score
f1 = f1_score(valid_ground_truth, valid_predictions, average='weighted')
print(f"F1 Score: {f1:.2f}")

# Display classification report
print("Classification Report:")
print(classification_report(valid_ground_truth, valid_predictions))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(valid_ground_truth, valid_predictions))


Accuracy: 0.14
F1 Score: 0.10
Classification Report:
              precision    recall  f1-score   support

          -3       0.00      0.00      0.00         0
          -2       0.00      0.00      0.00         0
          -1       0.00      0.00      0.00         0
           1       0.22      0.38      0.28        13
           2       0.12      0.45      0.19        11
           3       0.33      0.04      0.06        28
           4       0.00      0.00      0.00        15
           5       0.00      0.00      0.00        10

    accuracy                           0.14        77
   macro avg       0.08      0.11      0.07        77
weighted avg       0.18      0.14      0.10        77

Confusion Matrix:
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0  0  5  6  0  0  0]
 [ 2  0  0  3  5  1  0  0]
 [ 0  0  1  8 18  1  0  0]
 [ 1  0  0  3 10  1  0  0]
 [ 3  1  0  4  2  0  0  0]]


E:\xlpro-model\venv\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
E:\xlpro-model\venv\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
E:\xlpro-model\venv\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
E:\xlpro-model\venv\lib\site-packages\sklearn\metrics\_classifi

In [2]:
import torch
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from torch.utils.data import DataLoader
from data_utils import load_pickle
from models import BiLSTMWithAttention

# Define Dataset class
class FingeringDataset(torch.utils.data.Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)  # Input features
        self.y = torch.tensor(y, dtype=torch.long)  # Labels

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

# Main testing function
def test_model_on_train_data():
    # Load augmented training data
    X_train_aug = np.load('X_train_aug.npy')
    y_train_aug = np.load('y_train_aug.npy')

    # Load LabelEncoders
    le_fingering = load_pickle('le_fingering.pkl')

    # Model parameters
    input_size = X_train_aug.shape[2]  # Feature count
    hidden_size = 512
    num_layers = 3
    num_classes = 10
    dropout = 0.5

    # Initialize and load the trained model
    model = BiLSTMWithAttention(input_size, hidden_size, num_layers, num_classes, dropout)
    model.load_state_dict(torch.load('fingering_bilstm_model.pth', map_location=torch.device('cpu')))
    model.eval()

    # Create DataLoader for training data
    train_dataset = FingeringDataset(X_train_aug, y_train_aug)
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=False)

    # Evaluate the model on the training data
    y_true = []
    y_pred = []

    with torch.no_grad():
        for X_batch, y_batch in train_loader:
            outputs = model(X_batch)  # Predictions
            _, predicted = torch.max(outputs, 1)  # Get class with highest probability
            y_true.extend(y_batch.tolist())
            y_pred.extend(predicted.tolist())

    # Calculate performance metrics
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='macro')
    report = classification_report(y_true, y_pred)
    matrix = confusion_matrix(y_true, y_pred)

    print(f"Accuracy on Training Data: {accuracy:.4f}")
    print(f"F1 Score on Training Data: {f1:.4f}")
    print("Classification Report:")
    print(report)
    print("Confusion Matrix:")
    print(matrix)

if __name__ == "__main__":
    test_model_on_train_data()


Accuracy on Training Data: 0.8880
F1 Score on Training Data: 0.8876
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.85      0.90     11722
           1       0.84      0.95      0.89     11722
           2       0.92      0.89      0.90     11722
           3       0.90      0.91      0.90     11722
           4       0.94      0.93      0.93     11722
           5       0.89      0.91      0.90     11722
           6       0.85      0.84      0.84     11722
           7       0.85      0.80      0.83     11722
           8       0.87      0.83      0.85     11722
           9       0.88      0.96      0.92     11722

    accuracy                           0.89    117220
   macro avg       0.89      0.89      0.89    117220
weighted avg       0.89      0.89      0.89    117220

Confusion Matrix:
[[10008  1400    62    34   196    12     1     1     0     8]
 [  283 11186   207    28    17     0     1     0     0     0]
 [   4

In [1]:
import torch

# Load the trained model checkpoint
checkpoint = torch.load('fingering_bilstm_model.pth', map_location=torch.device('cpu'))

# Print model parameter shapes
for param_tensor, param in checkpoint.items():
    print(f"{param_tensor}: {param.size()}")


lstm.weight_ih_l0: torch.Size([2048, 136])
lstm.weight_hh_l0: torch.Size([2048, 512])
lstm.bias_ih_l0: torch.Size([2048])
lstm.bias_hh_l0: torch.Size([2048])
lstm.weight_ih_l0_reverse: torch.Size([2048, 136])
lstm.weight_hh_l0_reverse: torch.Size([2048, 512])
lstm.bias_ih_l0_reverse: torch.Size([2048])
lstm.bias_hh_l0_reverse: torch.Size([2048])
lstm.weight_ih_l1: torch.Size([2048, 1024])
lstm.weight_hh_l1: torch.Size([2048, 512])
lstm.bias_ih_l1: torch.Size([2048])
lstm.bias_hh_l1: torch.Size([2048])
lstm.weight_ih_l1_reverse: torch.Size([2048, 1024])
lstm.weight_hh_l1_reverse: torch.Size([2048, 512])
lstm.bias_ih_l1_reverse: torch.Size([2048])
lstm.bias_hh_l1_reverse: torch.Size([2048])
lstm.weight_ih_l2: torch.Size([2048, 1024])
lstm.weight_hh_l2: torch.Size([2048, 512])
lstm.bias_ih_l2: torch.Size([2048])
lstm.bias_hh_l2: torch.Size([2048])
lstm.weight_ih_l2_reverse: torch.Size([2048, 1024])
lstm.weight_hh_l2_reverse: torch.Size([2048, 512])
lstm.bias_ih_l2_reverse: torch.Size([204

In [ ]:
from sklearn.preprocessing import LabelEncoder

def replace_unseen_labels(df, column, le_pitch):
    """
    Replace unseen pitch labels in the dataset with the closest known label.

    Args:
    - df: DataFrame containing the pitch column.
    - column: Name of the column to process (e.g., 'normalized_spelled_pitch').
    - le_pitch: Trained LabelEncoder instance.

    Returns:
    - DataFrame with replaced labels.
    """
    known_classes = set(le_pitch.classes_)

    def find_closest_label(label):
        """
        Find the closest label to the unseen one based on pitch similarity.
        """
        if label in known_classes:
            return label
        # Extract pitch components (e.g., 'B7' -> 'B', '7')
        pitch_name, octave = label[:-1], label[-1]
        # Suggest replacement pitches within the same octave or neighboring ones
        replacements = [cls for cls in known_classes if cls[:-1] == pitch_name]
        if replacements:
            # Prefer the same pitch name
            return replacements[0]
        else:
            # Fall back to a known pitch (e.g., closest alphabetically)
            return min(known_classes, key=lambda x: abs(int(x[-1]) - int(octave)))

    # Replace unseen labels
    df[column] = df[column].apply(find_closest_label)
    return df

# Example usage
# Assuming `le_pitch` is your LabelEncoder instance
try:
    df['pitch_encoded'] = le_pitch.transform(df['normalized_spelled_pitch'])
except ValueError as e:
    print(f"Unseen labels detected: {e}")
    df = replace_unseen_labels(df, 'normalized_spelled_pitch', le_pitch)
    df['pitch_encoded'] = le_pitch.transform(df['normalized_spelled_pitch'])
