In [238]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu124


### Tensor: scalar, vector, matrix and tensor(multi-dimension）

In [239]:
scalar = torch.tensor(7)
vector = torch.tensor([7,7,7])
vector.ndim,scalar.ndim

(1, 0)

In [240]:
scalar.item()

7

In [241]:
vector.shape

torch.Size([3])

In [242]:
MATRIX = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
MATRIX.ndim,MATRIX.shape

(2, torch.Size([3, 2]))

In [243]:
TENSOR = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
TENSOR[1]

tensor([[5, 6],
        [7, 8]])

In [244]:
TENSOR.ndim

3

Random tensors
* can only be "float" datatype

In [245]:
random_tensor = torch.rand(3,10,10)
random_tensor

tensor([[[9.7008e-01, 4.3597e-02, 1.4656e-01, 8.7836e-01, 6.0104e-01,
          5.6984e-01, 6.6604e-01, 7.3410e-01, 3.2544e-01, 9.1806e-01],
         [5.7451e-01, 1.3452e-01, 6.8102e-01, 1.9899e-02, 2.1080e-01,
          2.2307e-01, 3.2381e-01, 6.4523e-01, 5.1591e-01, 9.0033e-01],
         [5.8057e-01, 1.9478e-01, 8.0593e-02, 3.1561e-02, 5.4439e-01,
          8.3066e-01, 6.9588e-01, 4.7957e-01, 7.0512e-01, 5.0644e-01],
         [2.9722e-01, 7.2275e-01, 1.6627e-01, 7.9851e-01, 1.7836e-01,
          3.1022e-01, 6.1694e-01, 8.0720e-01, 9.7179e-01, 8.1283e-01],
         [4.9459e-01, 4.9632e-01, 7.0065e-01, 4.1004e-01, 5.5040e-01,
          2.0647e-02, 9.1706e-01, 9.1643e-02, 5.1932e-01, 4.3074e-01],
         [3.8763e-01, 4.1699e-02, 8.5933e-01, 9.6661e-04, 7.2003e-01,
          5.6571e-02, 3.7805e-01, 8.5118e-01, 7.8433e-01, 7.6849e-02],
         [1.3973e-01, 6.7195e-01, 2.3281e-01, 3.1889e-01, 2.8863e-01,
          2.6897e-01, 1.6769e-02, 1.3650e-01, 4.8812e-01, 4.8237e-01],
         [9.2

In [246]:
random_tensor.ndim,random_tensor.dtype

(3, torch.float32)

In [247]:
random_image_size_tensor = torch.rand(size = (224,224,3)) 
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [248]:
zeros = torch.zeros(3,4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [249]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

creating range of tensors and tensors like

In [250]:
zero_to_nine = torch.arange(start=0,end = 10,step=2)
zero_to_nine

tensor([0, 2, 4, 6, 8])

In [251]:
ten_zeros = torch.zeros_like(input = zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0])

Tensor datatype-float16,float32,float64,int32,int64...

In [252]:
float_tensor = torch.tensor([3.0,6.0],
                            dtype=None, #datatype
                            device = "cuda", #device to run on
                            requires_grad=False) #tracking gradients with operation
float_tensor = float_tensor.type(torch.float16) 
float_tensor

tensor([3., 6.], device='cuda:0', dtype=torch.float16)

In [253]:
float_tensor * float_tensor.type(torch.int32)

tensor([ 9., 36.], device='cuda:0', dtype=torch.float16)

Information of tensor（整合）

In [254]:
rand_tensor = torch.rand(3,4)
rand_tensor.dtype,rand_tensor.shape,rand_tensor.ndim,rand_tensor.device,

(torch.float32, torch.Size([3, 4]), 2, device(type='cpu'))

Tensor operation

In [255]:
tensor = torch.tensor([1,2,3])
tensor = torch.sub(tensor,1)
torch.mul(tensor,10)

tensor([ 0, 10, 20])

In [256]:
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(3,4)
print(tensor1)
print(tensor2)
print(torch.matmul(tensor1,tensor2)) #can also use torch.mm

tensor([[0.2018, 0.8930, 0.2492],
        [0.0934, 0.2010, 0.3136]])
tensor([[0.3952, 0.1400, 0.1381, 0.6321],
        [0.1200, 0.3904, 0.7038, 0.3997],
        [0.0020, 0.5994, 0.8496, 0.9625]])
tensor([[0.1874, 0.5263, 0.8680, 0.7243],
        [0.0617, 0.2795, 0.4208, 0.4412]])


Transpose a matrix

In [257]:
tensor1 = torch.rand(3,2)
print(tensor1.shape,tensor2.shape)
tensor1 = tensor1.T #change to (2,3) matrix
torch.mm(tensor1,tensor2)

torch.Size([3, 2]) torch.Size([3, 4])


tensor([[0.1421, 0.7822, 1.2037, 1.1583],
        [0.3056, 0.9226, 1.4084, 1.4886]])

In [258]:
tensor1.shape,tensor2.shape

(torch.Size([2, 3]), torch.Size([3, 4]))

Tensor aggregation: finding min, max, mean, sum...

In [259]:
x = torch.arange(0,100,10)
x.min(),torch.min(x),x.max(),torch.max(x),x.sum(),torch.sum(x),x.type(torch.float32).mean(),torch.mean(x.type(torch.float32)) #mean function require float datatype

(tensor(0),
 tensor(0),
 tensor(90),
 tensor(90),
 tensor(450),
 tensor(450),
 tensor(45.),
 tensor(45.))

In [260]:
#find the position
x.argmin(),x.argmax(),x[x.argmin()],x[x.argmax()]

(tensor(0), tensor(9), tensor(0), tensor(90))

Reshaping, stacking, squeezing and unsqueezing tensors

In [261]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [262]:
# add a dimension- 元素数量须符合
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [263]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

* name.view与name.reshape的区别: name.view共享内存，name.reshape进行赋值

In [264]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [265]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [266]:
y = torch.zeros(2,1,2,1,2)