In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0rc1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\哈哈哈哈\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\哈哈哈哈\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\哈哈哈哈\Desktop\xlpro-model\venv\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\哈哈哈哈\Desktop\xlpro-model\venv\lib\site-packages\traitlets\config\application.py", li

2.4.0+cu124


### Tensor: scalar, vector, matrix and tensor(multi-dimension）

In [2]:
scalar = torch.tensor(7)
vector = torch.tensor([7,7,7])
vector.ndim,scalar.ndim

(1, 0)

In [3]:
scalar.item()

7

In [4]:
vector.shape

torch.Size([3])

In [5]:
MATRIX = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
MATRIX.ndim,MATRIX.shape

(2, torch.Size([3, 2]))

In [6]:
TENSOR = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
TENSOR[1]

tensor([[5, 6],
        [7, 8]])

In [7]:
TENSOR.ndim

3

Random tensors
* can only be "float" datatype

In [8]:
random_tensor = torch.rand(3,10,10)
random_tensor

tensor([[[3.8449e-01, 2.3293e-01, 5.3111e-01, 4.9190e-02, 5.5211e-01,
          8.8676e-01, 7.1503e-01, 2.2075e-01, 3.1290e-01, 7.8216e-01],
         [9.0546e-02, 2.8989e-01, 5.5144e-01, 7.7112e-01, 1.3534e-01,
          4.6394e-02, 7.2369e-01, 1.3506e-01, 5.5180e-01, 1.0774e-01],
         [9.5486e-01, 3.5520e-01, 5.7421e-02, 6.7198e-02, 2.0980e-01,
          7.7908e-01, 3.5360e-01, 4.8987e-01, 3.7274e-02, 5.9258e-01],
         [3.9708e-01, 3.4171e-01, 3.6869e-01, 2.4693e-01, 7.3277e-01,
          5.2842e-01, 4.9732e-01, 4.3425e-01, 6.5061e-01, 2.8146e-01],
         [6.3939e-01, 5.0104e-01, 1.9435e-01, 8.9700e-01, 7.3057e-01,
          9.1598e-01, 8.4290e-01, 4.8008e-02, 2.2906e-01, 6.0493e-01],
         [9.6446e-01, 6.5555e-01, 6.3580e-01, 8.5062e-01, 5.8084e-01,
          4.4731e-01, 9.6319e-01, 6.4050e-01, 1.8682e-02, 5.8645e-01],
         [7.9242e-01, 9.6296e-01, 8.1376e-01, 1.6862e-01, 5.1109e-02,
          3.4757e-01, 5.2657e-01, 9.8365e-01, 9.9572e-01, 9.9728e-01],
         [5.9

In [9]:
random_tensor.ndim,random_tensor.dtype

(3, torch.float32)

In [10]:
random_image_size_tensor = torch.rand(size = (224,224,3)) 
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [11]:
zeros = torch.zeros(3,4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [12]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

creating range of tensors and tensors like

In [13]:
zero_to_nine = torch.arange(start=0,end = 10,step=2)
zero_to_nine

tensor([0, 2, 4, 6, 8])

In [14]:
ten_zeros = torch.zeros_like(input = zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0])

Tensor datatype-float16,float32,float64,int32,int64...

In [15]:
float_tensor = torch.tensor([3.0,6.0],
                            dtype=None, #datatype
                            device = "cuda", #device to run on
                            requires_grad=False) #tracking gradients with operation
float_tensor = float_tensor.type(torch.float16) 
float_tensor

tensor([3., 6.], device='cuda:0', dtype=torch.float16)

In [16]:
float_tensor * float_tensor.type(torch.int32)

tensor([ 9., 36.], device='cuda:0', dtype=torch.float16)

Information of tensor（整合）

In [17]:
rand_tensor = torch.rand(3,4)
rand_tensor.dtype,rand_tensor.shape,rand_tensor.ndim,rand_tensor.device,

(torch.float32, torch.Size([3, 4]), 2, device(type='cpu'))

Tensor operation

In [18]:
tensor = torch.tensor([1,2,3])
tensor = torch.sub(tensor,1)
torch.mul(tensor,10)

tensor([ 0, 10, 20])

In [19]:
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(3,4)
print(tensor1)
print(tensor2)
print(torch.matmul(tensor1,tensor2)) #can also use torch.mm

tensor([[0.6799, 0.2793, 0.9860],
        [0.7774, 0.5820, 0.6771]])
tensor([[0.0075, 0.5533, 0.0436, 0.9525],
        [0.0182, 0.5498, 0.9337, 0.4388],
        [0.0621, 0.0520, 0.1179, 0.3474]])
tensor([[0.0714, 0.5810, 0.4067, 1.1127],
        [0.0585, 0.7854, 0.6571, 1.2312]])


Transpose a matrix

In [20]:
tensor1 = torch.rand(3,2)
print(tensor1.shape,tensor2.shape)
tensor1 = tensor1.T #change to (2,3) matrix
torch.mm(tensor1,tensor2)

torch.Size([3, 2]) torch.Size([3, 4])


tensor([[0.0541, 0.3279, 0.4226, 0.5794],
        [0.0424, 0.5428, 0.1216, 1.0727]])

In [21]:
tensor1.shape,tensor2.shape

(torch.Size([2, 3]), torch.Size([3, 4]))

Tensor aggregation: finding min, max, mean, sum...

In [22]:
x = torch.arange(0,100,10)
x.min(),torch.min(x),x.max(),torch.max(x),x.sum(),torch.sum(x),x.type(torch.float32).mean(),torch.mean(x.type(torch.float32)) #mean function require float datatype

(tensor(0),
 tensor(0),
 tensor(90),
 tensor(90),
 tensor(450),
 tensor(450),
 tensor(45.),
 tensor(45.))

In [25]:
#find the position
x.argmin(),x.argmax(),x[x.argmin()],x[x.argmax()]

(tensor(0), tensor(9), tensor(0), tensor(90))

Reshaping, stacking, squeezing and unsqueezing tensors

In [26]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [30]:
# add a dimension- 元素数量须符合
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [32]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

* name.view与name.reshape的区别: name.view共享内存，name.reshape进行赋值

In [34]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))